name: mytaste
description: A canteen Automation App


publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  provider: ^5.0.0
  geolocator: ^7.0.3
  google_fonts: ^2.0.0
  velocity_x: ^3.0.0
  shimmer: ^1.1.2
  cached_network_image: ^3.0.0
  alice: ^0.2.0
  firebase_core: "^1.1.0"
  firebase_auth: "^1.1.2"
  lottie: ^1.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_advanced_drawer: ^1.1.0
  firebase_storage: "^8.0.5"
  image_picker: ^0.7.5+2
  flutter_native_splash: ^1.1.8+4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icon.png

flutter_native_splash:
  image: assets/icon.png
  color: "#ffc260"

flutter:
  
  uses-material-design: true
  
  assets:
    - assets/json/dummypics.json
    - assets/json/foodList.json
    - assets/json/LoginLottie.json
    - assets/json/waiting.json
    - assets/json/waiting-pigeon.json
    - assets/json/confirm-order.json
    - assets/json/order-is-confirmed.json
    - assets/defaultProfileImage.jpg
  